# Generated by Django 5.1.1 on 2024-09-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='estado_pago',
            field=models.CharField(choices=[('P', 'Pagado'), ('N', 'No Pagado'), ('C', 'Cancelado')], max_length=20, verbose_name='Estado de Pago'),
        ),
    ]
