# Generated by Django 5.1 on 2024-10-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalRecords', '0001_initial'),
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(blank=True, max_length=100, verbose_name='Details')),
                ('paymentStatus', models.BooleanField(default=False)),
                ('idMedicalRecords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalRecords.medicalrecords')),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patients')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
    ]
