# Generated by Django 5.1.1 on 2024-09-22 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalRecords', '0003_remove_medicalrecord_descripcion_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_administracion', models.CharField(choices=[('Oral', 'Oral'), ('Intramuscular', 'Intramuscular'), ('Inhalatoria', 'Inhalatoria'), ('Tópica', 'Tópica')], default='Oral', max_length=20)),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración del tratamiento')),
                ('instrucciones', models.TextField(blank=True, null=True, verbose_name='Instrucciones adicionales')),
                ('fecha_prescripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Prescripción')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalRecords.medicalrecord', verbose_name='Historia Clínica')),
                ('medico', models.ForeignKey(limit_choices_to={'rol__nombre': 'Médico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
            ],
        ),
    ]
