# Generated by Django 5.1.1 on 2024-09-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalRecords', '0001_initial'),
        ('medicationInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_administracion', models.CharField(choices=[('Oral', 'Oral'), ('Intramuscular', 'Intramuscular'), ('Inhalatoria', 'Inhalatoria'), ('Tópica', 'Tópica')], default='Oral', max_length=20)),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duración del tratamiento')),
                ('instrucciones', models.TextField(blank=True, null=True, verbose_name='Instrucciones adicionales')),
                ('fecha_prescripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Prescripción')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalRecords.medicalrecord', verbose_name='Historia Clínica')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicationInventory.medicationinventory', verbose_name='Medicamento')),
            ],
        ),
    ]
