# Generated by Django 5.1.1 on 2024-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_prescription_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='fecha_prescripcion',
            field=models.DateTimeField(verbose_name='Fecha de Prescripción'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='via_administracion',
            field=models.CharField(max_length=20, verbose_name='Vía de Administración'),
        ),
    ]
