# Generated by Django 5.1.1 on 2024-10-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_alter_prescription_fecha_prescripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='fecha_prescripcion',
        ),
    ]
