# Generated by Django 5.1.1 on 2024-09-22 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('descripcion_diagnostico', models.TextField(verbose_name='Descripción del diagnóstico')),
                ('medico', models.ForeignKey(limit_choices_to={'rol__nombre': 'Médico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
            ],
        ),
    ]
