# Generated by Django 5.1.1 on 2024-09-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('descripcion_diagnostico', models.TextField(verbose_name='Descripción del diagnóstico')),
            ],
        ),
    ]
