# Generated by Django 5.1.1 on 2024-09-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalRecords', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='descripcion_diagnostico',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción del diagnóstico'),
            preserve_default=False,
        ),
    ]
