# Generated by Django 5.1.1 on 2024-10-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalRecords', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de Registro'),
        ),
    ]
