# Generated by Django 5.1.1 on 2024-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalRecords', '0003_alter_medicalrecord_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='fecha_registro',
            field=models.DateTimeField(verbose_name='Fecha de Registro'),
        ),
    ]
