# Generated by Django 5.1.1 on 2024-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalRecords', '0004_alter_medicalrecord_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='motivo_consulta',
            field=models.TextField(default='s', verbose_name='Motivo de consulta'),
            preserve_default=False,
        ),
    ]
