# Generated by Django 5.1.1 on 2024-09-22 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medico',
            field=models.ForeignKey(default='1', limit_choices_to={'rol__nombre': 'Médico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
            preserve_default=False,
        ),
    ]
