# Generated by Django 5.1.1 on 2024-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultationType', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationtype',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio base'),
        ),
    ]
