# Generated by Django 5.1.1 on 2024-09-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('contacto_emergencia', models.IntegerField(verbose_name='Contacto de Emergencia')),
                ('numero_poliza', models.IntegerField(verbose_name='Número de Poliza')),
                ('estado_poliza', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva'), ('E', 'Expirada')], max_length=1, verbose_name='Estado de Póliza')),
                ('vigencia_poliza', models.DateField(verbose_name='Vigencia de Poliza')),
            ],
        ),
    ]
